name: Email Action

on:
  workflow_dispatch:   # Allows manual triggering from GitHub
  push:                # Also triggers on push

jobs:
  test:
    runs-on: ubuntu-latest        # <-- Add this line
    steps:
      - name: 23f3003728@ds.study.iitm.ac.in
        run: echo "Hello, world!"

